permalink: /:year:month:day/:title
url: https://cdpyufal.github.io
baseurl: /project

# variables
name: CD Py | UFAL
description: Coding Dojo CTEC Group
google_verification: null

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true
